#!/bin/bash

HERE="`dirname "$0"`"
cd "$HERE"

if [ "$ILABS_SWAPKIT_IPHONE_SDK_VERSION" == "" ]; then
    ILABS_SWAPKIT_IPHONE_SDK_VERSION=3.1.2
fi

if [ "$ILABS_SWAPKIT_CONFIGURATION" == "" ]; then
    ILABS_SWAPKIT_CONFIGURATION=Debug
fi

# TODO have ILABS_SWAPKIT_EXTRA_BUILD_FLAGS as an array to work around the spaces mess.

echo " ~ Building the Simulator SDK static library ~ "

xcodebuild -project SwapKit.xcodeproj -configuration "$ILABS_SWAPKIT_CONFIGURATION" -target "SwapKit" -sdk iphonesimulator"$ILABS_SWAPKIT_IPHONE_SDK_VERSION" $ILABS_SWAPKIT_EXTRA_BUILD_FLAGS clean build || exit 1

echo " ~ Building the Device SDK static library ~ "

xcodebuild -project SwapKit.xcodeproj -configuration "$ILABS_SWAPKIT_CONFIGURATION" -target "SwapKit" -sdk iphoneos"$ILABS_SWAPKIT_IPHONE_SDK_VERSION" $ILABS_SWAPKIT_EXTRA_BUILD_FLAGS clean build || exit 1

echo " ~ Building the Framework ~ "

xcodebuild -project SwapKit.xcodeproj -configuration "$ILABS_SWAPKIT_CONFIGURATION" -target "SwapKit (Framework)" $ILABS_SWAPKIT_EXTRA_BUILD_FLAGS clean build || exit 1

